"""initial migration

Revision ID: 7e371c380541
Revises: 
Create Date: 2026-03-02 18:26:25.886890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e371c380541'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Not dropping tables to preserve existing data
    op.create_table('subscription_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed: op.drop_table('subscription_transaction') - Keeping existing tables
    # Made nullable=True since table already has data
    op.add_column('chat_message', sa.Column('rag_mode', sa.Enum('VECTOR', 'PAGE_INDEX', 'HYBRID', name='rag_mode_enum'), nullable=True))
    op.add_column('chat_message', sa.Column('page_references', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'page_references')
    op.drop_column('chat_message', 'rag_mode')
    op.create_table('subscription_transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_plan', postgresql.ENUM('FREE', 'BRONZE', 'SILVER', 'GOLD', name='subscription_level'), autoincrement=False, nullable=False),
    sa.Column('new_plan', postgresql.ENUM('FREE', 'BRONZE', 'SILVER', 'GOLD', name='subscription_level'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_detailes.id'], name=op.f('subscription_transaction_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_transaction_pkey'))
    )
    op.drop_table('subscription_transactions')
    # ### end Alembic commands ###
