"""add rag_mode and document_pages

Revision ID: a774ba58bd85
Revises: 7e371c380541
Create Date: 2026-03-02 18:40:09.173507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a774ba58bd85'
down_revision: Union[str, Sequence[str], None] = '7e371c380541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed: op.drop_table('subscription_transaction') - Keep existing tables
    # Removed: op.alter_column to NOT NULL - table has existing data with NULL values
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes needed for downgrade since we didn't modify anything
    # ### end Alembic commands ###
