class CommonHTTPMessage:
    OK = "Success"
    CREATED = "Resource created successfully"
    BAD_REQUEST = "Bad request"
    UNAUTHORIZED = "Unauthorized access"
    FORBIDDEN = "Access forbidden"
    NOT_FOUND = "Resource not found"
    VALIDATION_ERROR = "Validation error"
    INTERNAL_SERVER_ERROR = "Internal server error"
    DATABASE_ERROR = "Database error"
    GENAI_ERROR = "GenAI processing failed"
    USER_PRESENT = "This Information is already Present"
